name: Code Quality Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Check code formatting and style
        run: |
          # Check for common C++ style issues
          echo "Checking for basic code style issues..."

          # Check for trailing whitespace
          if grep -r --include="*.cpp" --include="*.h" --include="*.ino" '[[:space:]]$' src/ include/ || true; then
            echo "Warning: Found trailing whitespace in source files"
          fi

          # Check for tabs (should use spaces)
          if grep -r --include="*.cpp" --include="*.h" --include="*.ino" $'\t' src/ include/ || true; then
            echo "Warning: Found tabs in source files (consider using spaces)"
          fi

          # Check for long lines (>120 characters)
          if grep -r --include="*.cpp" --include="*.h" --include="*.ino" '.\{121,\}' src/ include/ || true; then
            echo "Warning: Found lines longer than 120 characters"
          fi

      - name: Check include guards
        run: |
          echo "Checking header files for include guards..."
          for file in include/*.h; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .h | tr '[:lower:]' '[:upper:]' | tr '.' '_')
              guard_name="${filename}_H"
              if ! grep -q "#ifndef.*${guard_name}" "$file" && ! grep -q "#pragma once" "$file"; then
                echo "Warning: $file may be missing include guards"
              fi
            fi
          done

      - name: Check for TODO/FIXME comments
        run: |
          echo "Checking for TODO/FIXME comments..."
          grep -r --include="*.cpp" --include="*.h" --include="*.ino" -n "TODO\|FIXME\|XXX" src/ include/ || echo "No TODO/FIXME comments found"

      - name: Syntax check with PlatformIO
        run: |
          echo "Performing syntax check..."
          pio check --fail-on-defect=low --skip-packages
