name: Release Build

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build release firmware
        run: |
          echo "Building release firmware for version ${{ steps.get_version.outputs.VERSION }}"
          pio run -e esp32dev

      - name: Prepare release artifacts
        run: |
          mkdir -p release-artifacts
          cp .pio/build/esp32dev/firmware.bin release-artifacts/payload-firmware-${{ steps.get_version.outputs.VERSION }}.bin
          cp .pio/build/esp32dev/firmware.elf release-artifacts/payload-firmware-${{ steps.get_version.outputs.VERSION }}.elf

          # Create checksums
          cd release-artifacts
          sha256sum *.bin *.elf > checksums.txt
          cd ..

          # Create release info
          echo "# CanSat Payload Firmware ${{ steps.get_version.outputs.VERSION }}" > release-artifacts/README.md
          echo "" >> release-artifacts/README.md
          echo "## Build Information" >> release-artifacts/README.md
          echo "- **Version:** ${{ steps.get_version.outputs.VERSION }}" >> release-artifacts/README.md
          echo "- **Built on:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> release-artifacts/README.md
          echo "- **Commit:** ${{ github.sha }}" >> release-artifacts/README.md
          echo "- **Target:** ESP32" >> release-artifacts/README.md
          echo "" >> release-artifacts/README.md
          echo "## Files" >> release-artifacts/README.md
          echo "- \`payload-firmware-${{ steps.get_version.outputs.VERSION }}.bin\` - Main firmware binary" >> release-artifacts/README.md
          echo "- \`payload-firmware-${{ steps.get_version.outputs.VERSION }}.elf\` - Debug symbols (for debugging)" >> release-artifacts/README.md
          echo "- \`checksums.txt\` - SHA256 checksums for verification" >> release-artifacts/README.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-artifacts/*
          body_path: release-artifacts/README.md
          draft: false
          prerelease: false
          name: CanSat Payload Firmware ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
